name: 'gopxl docs'
author: 'Mark Kremer'
description: 'A static website generator for the gopxl Markdown documentation'
inputs:
  site-url:
    description: "URL the site will be deployed to (https://owner.github.com/project)"
    required: true
  github-url:
    description: "URL to the Github repository"
    default: ${{ github.server_url }}/${{ github.repository }}
  docs-directory:
    description: 'Path to the documentation directory inside the repository'
    required: false
    default: 'docs'
  output-directory:
    description: 'Directory the generated files will be put in'
    required: false
    default: '_site/'
  main-branch:
    description: 'Branch to publish alongside tagged versions'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SITE_URL: ${{ inputs.site-url }}
    GITHUB_URL: ${{ inputs.github-url }}
    REPOSITORY_PATH: ./
    DOCS_DIR: ${{ inputs.docs-directory }}
    OUTPUT_DIR: ${{ inputs.destination-directory }}
    MAIN_BRANCH: ${{ inputs.main-branch }}
