name: 'gopxl docs'
author: 'Mark Kremer'
description: 'A static website generator for the gopxl Markdown documentation'
inputs:
  docs-directory:
    description: 'Path to the documentation directory inside the repository'
    required: false
    default: 'docs'
  output-directory:
    description: 'Directory the generated files will be put in'
    required: false
    default: '_site/'
  site-url:
    description: "URL the site will be deployed to (https://owner.github.com/project)"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SITE_URL: ${{ inputs.deploy-url }}
    REPOSITORY_URL: ${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}
    REPOSITORY_PATH: ./
    DOCS_DIR: ${{ inputs.docs-directory }}
    OUTPUT_DIR: ${{ inputs.destination-directory }}
