name: 'gopxl docs'
author: 'Mark Kremer'
description: 'A static website generator for the gopxl Markdown documentation'
inputs:
  github-url:
    description: "URL to the Github repository"
    default: ${{ github.server_url }}/${{ github.repository }}
  docs-directory:
    description: 'Path to the documentation directory inside the repository'
    required: false
    default: 'docs'
  output-directory:
    description: 'Directory the generated files will be put in'
    required: false
    default: '_site/'
  main-branch:
    description: 'Branch to publish alongside tagged versions'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure pages
      uses: actions/configure-pages@v5
      id: configure-pages
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.main-branch }}
        fetch-depth: 0 # checkout a non-shallow copy so the generator can generate docs for all major versions
    - name: Generate static site
      uses: ./.github/actions/docgen
      with:
        site-url: ${{ steps.configure-pages.outputs.base_url }}
        github-url: ${{ inputs.github-url }}
        docs-directory: ${{ inputs.docs-directory }}
        output-directory: ${{ inputs.output-directory }}
        main-branch: ${{ inputs.main-branch }}
    - name: Upload pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.OUTPUT_DIR }}
    - name: Deploy pages
      uses: actions/deploy-pages@v4
