name: GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches: ['main']

jobs:

  upload-docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:
      DOCS_DIR: 'docs/'
      OUTPUT_DIR: '_site/'
      BRANCH: 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        with:
          docs-directory: ${{ env.DOCS_DIR }}
          output-directory: ${{ env.OUTPUT_DIR }}
          main-branch: ${{ env.BRANCH }}
