name: GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches: ['main']

jobs:

  upload-docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:
      DOCS_DIR: 'docs/'
      DEST_DIR: '_site/'
      BRANCH: 'main'
    steps:
      - uses: actions/configure-pages@v5
        id: configure-pages
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0 # checkout a non-shallow copy so the generator can generate docs for all major versions
      - uses: ./
        with:
          deploy-url: ${{ steps.configure-pages.outputs.base_url }}
          docs-directory: ${{ env.DOCS_DIR }}
          destination-directory: ${{ env.DEST_DIR }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DEST_DIR }}
      - uses: actions/deploy-pages@v4
